# coding: utf-8

"""
    Employee API

    Endpoints of CRUD of employee.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.employee_api import EmployeeApi


class TestEmployeeApi(unittest.TestCase):
    """EmployeeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeeApi()

    def tearDown(self) -> None:
        pass

    def test_api_employee_get(self) -> None:
        """Test case for api_employee_get

        Returns all employee.
        """
        pass

    def test_api_employee_id_delete(self) -> None:
        """Test case for api_employee_id_delete

        """
        pass

    def test_api_employee_id_get(self) -> None:
        """Test case for api_employee_id_get

        Returns employee of given id
        """
        pass

    def test_api_employee_id_put(self) -> None:
        """Test case for api_employee_id_put

        Updates employee details
        """
        pass

    def test_api_employee_post(self) -> None:
        """Test case for api_employee_post

        Adds new employee
        """
        pass


if __name__ == '__main__':
    unittest.main()
